# .github/workflows/metrics.yml
name: Metrics
on:
  # Roda a cada 24 horas e também ao fazer push para a branch main
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Seu token do GitHub
          token: ${{ secrets.GITHUB_TOKEN }}

          # Opções
          user: MaiconAvila # Substitua pelo seu nome de usuário
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
